void beginServo();
void updateServo();
void onDispenser();
void onDispenserSettings();
void onDispenserStop();
void onDispenserAnimation();
void onServoHandlerMove();
void onServoHandlerStop();
void attachServoCommands();
