# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bottleParameter.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_bottleParameter(object):
    def setupUi(self, bottleParameter):
        bottleParameter.setObjectName("bottleParameter")
        bottleParameter.resize(100, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(bottleParameter.sizePolicy().hasHeightForWidth())
        bottleParameter.setSizePolicy(sizePolicy)
        bottleParameter.setMinimumSize(QtCore.QSize(100, 100))
        bottleParameter.setMaximumSize(QtCore.QSize(100, 100))
        bottleParameter.setStyleSheet("QFrame {\n"
"    background-color: #FFFFFF; /* Par exemple, fond blanc par défaut */\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QFrame:pressed {\n"
"    background-color: #EAEAEA; /* Fond gris clair lorsque le QFrame est appuyé */\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(bottleParameter)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(bottleParameter)
        font = QtGui.QFont()
        font.setFamily("CoconPro")
        font.setPointSize(-1)
        font.setUnderline(False)
        self.title.setFont(font)
        self.title.setStyleSheet("font-size: 12px;\n"
"color: black;")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.content = QtWidgets.QLabel(bottleParameter)
        font = QtGui.QFont()
        font.setFamily("CoconPro")
        font.setPointSize(-1)
        self.content.setFont(font)
        self.content.setStyleSheet("font-size: 10px;\n"
"color: black;")
        self.content.setAlignment(QtCore.Qt.AlignCenter)
        self.content.setObjectName("content")
        self.verticalLayout.addWidget(self.content)
        self.quantity = QtWidgets.QLabel(bottleParameter)
        font = QtGui.QFont()
        font.setFamily("CoconPro")
        font.setPointSize(-1)
        self.quantity.setFont(font)
        self.quantity.setStyleSheet("font-size: 10px;\n"
"color: black;")
        self.quantity.setAlignment(QtCore.Qt.AlignCenter)
        self.quantity.setObjectName("quantity")
        self.verticalLayout.addWidget(self.quantity)

        self.retranslateUi(bottleParameter)
        QtCore.QMetaObject.connectSlotsByName(bottleParameter)

    def retranslateUi(self, bottleParameter):
        _translate = QtCore.QCoreApplication.translate
        bottleParameter.setWindowTitle(_translate("bottleParameter", "Frame"))
        self.title.setText(_translate("bottleParameter", "Bouteille 1"))
        self.content.setText(_translate("bottleParameter", "Rhum Blanc"))
        self.quantity.setText(_translate("bottleParameter", "100 ml"))
