# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cocktailStep.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cocktailStep(object):
    def setupUi(self, cocktailStep):
        cocktailStep.setObjectName("cocktailStep")
        cocktailStep.resize(400, 120)
        self.subtitle = QtWidgets.QLabel(cocktailStep)
        self.subtitle.setGeometry(QtCore.QRect(0, 40, 400, 30))
        font = QtGui.QFont()
        font.setFamily("CoconPro")
        font.setPointSize(-1)
        self.subtitle.setFont(font)
        self.subtitle.setStyleSheet("font-size: 20px;\n"
"color: black;")
        self.subtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitle.setObjectName("subtitle")
        self.stepTitle = QtWidgets.QLabel(cocktailStep)
        self.stepTitle.setGeometry(QtCore.QRect(0, 0, 400, 40))
        font = QtGui.QFont()
        font.setFamily("CoconPro")
        font.setPointSize(-1)
        self.stepTitle.setFont(font)
        self.stepTitle.setStyleSheet("font-size: 30px;\n"
"color: black;")
        self.stepTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.stepTitle.setObjectName("stepTitle")

        self.retranslateUi(cocktailStep)
        QtCore.QMetaObject.connectSlotsByName(cocktailStep)

    def retranslateUi(self, cocktailStep):
        _translate = QtCore.QCoreApplication.translate
        self.subtitle.setText(_translate("cocktailStep", "Déposez un verre sur la machine"))
        self.stepTitle.setText(_translate("cocktailStep", "Étape 1 : Mettre un verre"))
