# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cocktailStep2Button.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cocktailStep2Button(object):
    def setupUi(self, cocktailStep2Button):
        cocktailStep2Button.setObjectName("cocktailStep2Button")
        cocktailStep2Button.resize(800, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(cocktailStep2Button.sizePolicy().hasHeightForWidth())
        cocktailStep2Button.setSizePolicy(sizePolicy)
        cocktailStep2Button.setMinimumSize(QtCore.QSize(800, 200))
        cocktailStep2Button.setMaximumSize(QtCore.QSize(800, 200))
        self.stepTitle = QtWidgets.QLabel(cocktailStep2Button)
        self.stepTitle.setGeometry(QtCore.QRect(0, 0, 800, 40))
        font = QtGui.QFont()
        font.setFamily("CoconPro")
        font.setPointSize(-1)
        self.stepTitle.setFont(font)
        self.stepTitle.setStyleSheet("font-size: 30px;\n"
"color: black;")
        self.stepTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.stepTitle.setObjectName("stepTitle")
        self.subtitle = QtWidgets.QLabel(cocktailStep2Button)
        self.subtitle.setGeometry(QtCore.QRect(0, 40, 800, 30))
        font = QtGui.QFont()
        font.setFamily("CoconPro")
        font.setPointSize(-1)
        self.subtitle.setFont(font)
        self.subtitle.setStyleSheet("font-size: 20px;\n"
"color: black;")
        self.subtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitle.setObjectName("subtitle")
        self.button_1 = QtWidgets.QPushButton(cocktailStep2Button)
        self.button_1.setGeometry(QtCore.QRect(320, 80, 60, 30))
        self.button_1.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background-color: #F79643;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0; /* Gris clair lorsqu\'appuyé */\n"
"}\n"
"")
        self.button_1.setObjectName("button_1")
        self.button_2 = QtWidgets.QPushButton(cocktailStep2Button)
        self.button_2.setGeometry(QtCore.QRect(420, 80, 60, 30))
        self.button_2.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background-color: #F79643;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0; /* Gris clair lorsqu\'appuyé */\n"
"}\n"
"")
        self.button_2.setObjectName("button_2")

        self.retranslateUi(cocktailStep2Button)
        QtCore.QMetaObject.connectSlotsByName(cocktailStep2Button)

    def retranslateUi(self, cocktailStep2Button):
        _translate = QtCore.QCoreApplication.translate
        self.stepTitle.setText(_translate("cocktailStep2Button", "Étape 1 : Citron"))
        self.subtitle.setText(_translate("cocktailStep2Button", "Y-a-t-il des citron dans le bol ?"))
        self.button_1.setText(_translate("cocktailStep2Button", "Oui"))
        self.button_2.setText(_translate("cocktailStep2Button", "Non"))
