# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cocktailCard.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cocktailCard(object):
    def setupUi(self, cocktailCard):
        cocktailCard.setObjectName("cocktailCard")
        cocktailCard.resize(130, 130)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(cocktailCard.sizePolicy().hasHeightForWidth())
        cocktailCard.setSizePolicy(sizePolicy)
        cocktailCard.setMinimumSize(QtCore.QSize(130, 130))
        cocktailCard.setMaximumSize(QtCore.QSize(130, 130))
        cocktailCard.setStyleSheet("background-color: #FFFFFF; /* Couleur de fond blanc */\n"
"border-radius: 15px; /* Bords arrondis de 5px */")
        self.cocktailCardImage = QtWidgets.QLabel(cocktailCard)
        self.cocktailCardImage.setEnabled(True)
        self.cocktailCardImage.setGeometry(QtCore.QRect(40, 10, 51, 71))
        font = QtGui.QFont()
        font.setFamily("CoconPro")
        font.setPointSize(-1)
        self.cocktailCardImage.setFont(font)
        self.cocktailCardImage.setStyleSheet("color: black;\n"
"font-size: 16px;")
        self.cocktailCardImage.setText("")
        self.cocktailCardImage.setPixmap(QtGui.QPixmap("ressources/cocktail/spritz.png"))
        self.cocktailCardImage.setScaledContents(True)
        self.cocktailCardImage.setAlignment(QtCore.Qt.AlignCenter)
        self.cocktailCardImage.setObjectName("cocktailCardImage")
        self.cocktailCardName = QtWidgets.QLabel(cocktailCard)
        self.cocktailCardName.setEnabled(True)
        self.cocktailCardName.setGeometry(QtCore.QRect(10, 80, 111, 51))
        font = QtGui.QFont()
        font.setFamily("CoconPro")
        font.setPointSize(-1)
        self.cocktailCardName.setFont(font)
        self.cocktailCardName.setStyleSheet("color: black;\n"
"font-size: 16px;")
        self.cocktailCardName.setAlignment(QtCore.Qt.AlignCenter)
        self.cocktailCardName.setWordWrap(True)
        self.cocktailCardName.setObjectName("cocktailCardName")

        self.retranslateUi(cocktailCard)
        QtCore.QMetaObject.connectSlotsByName(cocktailCard)

    def retranslateUi(self, cocktailCard):
        _translate = QtCore.QCoreApplication.translate
        cocktailCard.setWindowTitle(_translate("cocktailCard", "Frame"))
        self.cocktailCardName.setText(_translate("cocktailCard", "Mojito"))
