# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dispenserControl.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dispenserControl(object):
    def setupUi(self, dispenserControl):
        dispenserControl.setObjectName("dispenserControl")
        dispenserControl.resize(100, 110)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dispenserControl.sizePolicy().hasHeightForWidth())
        dispenserControl.setSizePolicy(sizePolicy)
        dispenserControl.setMinimumSize(QtCore.QSize(100, 100))
        dispenserControl.setStyleSheet("font-family: \"CoconPro\";")
        self.titleLabel = QtWidgets.QLabel(dispenserControl)
        self.titleLabel.setGeometry(QtCore.QRect(10, 10, 80, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        self.titleLabel.setMinimumSize(QtCore.QSize(80, 30))
        self.titleLabel.setStyleSheet("color: black;\n"
"font-size: 12px;\n"
"border-radius: 8px;\n"
"background-color: #A0ACB0;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.pushButton = QtWidgets.QPushButton(dispenserControl)
        self.pushButton.setGeometry(QtCore.QRect(30, 60, 41, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    background-color: #F79643;\n"
"    border: 5px solid #707070; /* Bordure de 1px en noir */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FFBC50; /* Fond gris clair pour les boutons enfoncés */\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(dispenserControl)
        QtCore.QMetaObject.connectSlotsByName(dispenserControl)

    def retranslateUi(self, dispenserControl):
        _translate = QtCore.QCoreApplication.translate
        dispenserControl.setWindowTitle(_translate("dispenserControl", "Frame"))
        self.titleLabel.setText(_translate("dispenserControl", "Bouteille 1"))
