# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extraBottle.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_extraBottle(object):
    def setupUi(self, extraBottle):
        extraBottle.setObjectName("extraBottle")
        extraBottle.resize(100, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(extraBottle.sizePolicy().hasHeightForWidth())
        extraBottle.setSizePolicy(sizePolicy)
        extraBottle.setMinimumSize(QtCore.QSize(100, 100))
        extraBottle.setMaximumSize(QtCore.QSize(100, 100))
        extraBottle.setStyleSheet("font-family: \"CoconPro\";")
        self.pushButtonLeft = QtWidgets.QPushButton(extraBottle)
        self.pushButtonLeft.setGeometry(QtCore.QRect(0, 50, 31, 41))
        self.pushButtonLeft.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #FFBC50; \n"
"}")
        self.pushButtonLeft.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ressources/generic/arrow_left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonLeft.setIcon(icon)
        self.pushButtonLeft.setObjectName("pushButtonLeft")
        self.titleLabel = QtWidgets.QLabel(extraBottle)
        self.titleLabel.setGeometry(QtCore.QRect(10, 0, 81, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        self.titleLabel.setMinimumSize(QtCore.QSize(80, 30))
        self.titleLabel.setStyleSheet("color: black;\n"
"font-size: 12px;\n"
"border-radius: 8px;\n"
"background-color: #A0ACB0;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setWordWrap(True)
        self.titleLabel.setObjectName("titleLabel")
        self.lineEdit = QtWidgets.QLineEdit(extraBottle)
        self.lineEdit.setGeometry(QtCore.QRect(30, 50, 41, 41))
        self.lineEdit.setStyleSheet("border: 0px;\n"
"border-radius: 0px;\n"
"color: black;\n"
"font-size: 12px;\n"
"background-color: white;")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButtonRight = QtWidgets.QPushButton(extraBottle)
        self.pushButtonRight.setGeometry(QtCore.QRect(70, 50, 31, 41))
        self.pushButtonRight.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #FFBC50;\n"
"}")
        self.pushButtonRight.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ressources/generic/arrow_right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRight.setIcon(icon1)
        self.pushButtonRight.setObjectName("pushButtonRight")

        self.retranslateUi(extraBottle)
        QtCore.QMetaObject.connectSlotsByName(extraBottle)

    def retranslateUi(self, extraBottle):
        _translate = QtCore.QCoreApplication.translate
        extraBottle.setWindowTitle(_translate("extraBottle", "Frame"))
        self.titleLabel.setText(_translate("extraBottle", "Bouteille 1 Rhum"))
