# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ingredientCardDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ingredientCardDialog(object):
    def setupUi(self, ingredientCardDialog):
        ingredientCardDialog.setObjectName("ingredientCardDialog")
        ingredientCardDialog.resize(450, 144)
        ingredientCardDialog.setStyleSheet("font-family: \"CoconPro\";\n"
"background-color: #F9F8F8;\n"
"border-radius: 15px;\n"
"color: black; /* Définit la couleur du texte à noir */")
        self.label = QtWidgets.QLabel(ingredientCardDialog)
        self.label.setGeometry(QtCore.QRect(60, 20, 81, 21))
        self.label.setStyleSheet("font-family: \"CoconPro\";\n"
"background-color: #F9F8F8;\n"
"color: black;\n"
"font-size: 16px;")
        self.label.setObjectName("label")
        self.bottleComboBox = QtWidgets.QComboBox(ingredientCardDialog)
        self.bottleComboBox.setGeometry(QtCore.QRect(30, 50, 141, 61))
        self.bottleComboBox.setStyleSheet("QComboBox {\n"
"    background-color: #F9F8F8; /* Fond gris clair */\n"
"    color: #000000; /* Texte noir */\n"
"    font-size: 16px; /* Taille de la police 12 */\n"
"    border: 1px solid #707070; /* Bordure de 1px en noir */\n"
"    border-radius: 3px; /* Coins arrondis de 2px */\n"
"    padding: 2px; /* Espacement interne */\n"
"    selection-background-color: #FFA500; /* Fond d\'écran de sélection orange */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color: #F79643; /* Couleur de fond de la flèche déroulante (même que le fond) */\n"
"    border: 0px solid #707070; /* Bordure de la flèche déroulante en noir */\n"
"    width: 20px; /* Largeur de la flèche déroulante de 20px */\n"
"    margin-right: 0px; /* Marge à droite de la flèche déroulante */\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(./ressources/generic/arrow_down.svg); /* Chemin relatif vers votre icône SVG */\n"
"    color: #000000; /* Couleur de la flèche en noir */\n"
"}\n"
"\n"
"\n"
"")
        self.bottleComboBox.setObjectName("bottleComboBox")
        self.label_2 = QtWidgets.QLabel(ingredientCardDialog)
        self.label_2.setGeometry(QtCore.QRect(210, 20, 81, 21))
        self.label_2.setStyleSheet("font-family: \"CoconPro\";\n"
"background-color: #F9F8F8;\n"
"color: black;\n"
"font-size: 16px;")
        self.label_2.setObjectName("label_2")
        self.quantitySpinBox = QtWidgets.QSpinBox(ingredientCardDialog)
        self.quantitySpinBox.setGeometry(QtCore.QRect(190, 50, 121, 61))
        self.quantitySpinBox.setStyleSheet("QSpinBox {\n"
"    background-color: #F9F8F8; /* Fond gris clair */\n"
"    color: #000000; /* Texte noir */\n"
"    font-size: 20px; /* Taille de la police 12 */\n"
"    border: 1px solid #707070; /* Bordure de 1px en noir */\n"
"    border-radius: 3px; /* Coins arrondis de 3px */\n"
"    padding: 2px; /* Espacement interne */\n"
"    selection-background-color: transparent;\n"
"}\n"
"\n"
"QSpinBox::up-button, QSpinBox::down-button {\n"
"    background-color: #F79643; /* Couleur de fond des boutons d\'incrémentation/décrémentation */\n"
"    width: 20px; /* Largeur des boutons */\n"
"    border: 0px solid #707070; /* Bordure des boutons en noir */\n"
"    margin: 0px; /* Marge des boutons */\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right;\n"
"}\n"
"\n"
"QSpinBox::up-arrow{\n"
"    image: url(./ressources/generic/arrow_up.svg); /* Chemin relatif vers votre icône SVG */\n"
"    color: #000000; /* Couleur des flèches en noir */\n"
"}\n"
"QSpinBox::down-arrow {\n"
"    image: url(./ressources/generic/arrow_down.svg); /* Chemin relatif vers votre icône SVG */\n"
"    color: #000000; /* Couleur des flèches en noir */\n"
"}")
        self.quantitySpinBox.setFrame(False)
        self.quantitySpinBox.setMaximum(100)
        self.quantitySpinBox.setSingleStep(5)
        self.quantitySpinBox.setProperty("value", 100)
        self.quantitySpinBox.setDisplayIntegerBase(10)
        self.quantitySpinBox.setObjectName("quantitySpinBox")
        self.buttonBox = QtWidgets.QDialogButtonBox(ingredientCardDialog)
        self.buttonBox.setGeometry(QtCore.QRect(340, 40, 91, 71))
        self.buttonBox.setStyleSheet("/* Style pour tous les boutons QDialogButton */\n"
"QDialogButtonBox {\n"
"    background-color: transparent; /* Fond transparent */\n"
"    border: none; /* Pas de bordure */\n"
"    spacing: 10px; /* Espacement entre les boutons */\n"
"}\n"
"\n"
"/* Style spécifique pour le bouton \"Valider\" */\n"
"QDialogButtonBox QPushButton:enabled {\n"
"    background-color: #F79643; /* Fond orange pour le bouton \"Valider\" */\n"
"    color: #FFFFFF; /* Texte en blanc */\n"
"    border: 1px solid #FFA500; /* Bordure orange */\n"
"    border-radius: 3px; /* Coins arrondis de 3px */\n"
"    padding: 5px 10px; /* Espacement interne */\n"
"    font-size: 12px; /* Taille de la police 12 */\n"
"}\n"
"\n"
"/* Style pour les autres boutons (Annuler, etc.) */\n"
"QDialogButtonBox QPushButton:enabled:hover {\n"
"    background-color: #F79643; /* Fond orange clair au survol */\n"
"    border: 1px solid #F79643; /* Bordure orange clair au survol */\n"
"}\n"
"\n"
"/* Style pour les boutons désactivés */\n"
"QDialogButtonBox QPushButton:disabled {\n"
"    background-color: transparent; /* Fond transparent pour les boutons désactivés */\n"
"    color: #C0C0C0; /* Texte en gris pour les boutons désactivés */\n"
"    border: 1px solid #C0C0C0; /* Bordure grise pour les boutons désactivés */\n"
"}\n"
"")
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(ingredientCardDialog)
        QtCore.QMetaObject.connectSlotsByName(ingredientCardDialog)

    def retranslateUi(self, ingredientCardDialog):
        _translate = QtCore.QCoreApplication.translate
        ingredientCardDialog.setWindowTitle(_translate("ingredientCardDialog", "Dialog"))
        self.label.setText(_translate("ingredientCardDialog", "Contenu"))
        self.label_2.setText(_translate("ingredientCardDialog", "Quantité"))
