# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ingredientCard.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ingredientCard(object):
    def setupUi(self, ingredientCard):
        ingredientCard.setObjectName("ingredientCard")
        ingredientCard.resize(100, 40)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ingredientCard.sizePolicy().hasHeightForWidth())
        ingredientCard.setSizePolicy(sizePolicy)
        ingredientCard.setMinimumSize(QtCore.QSize(100, 40))
        ingredientCard.setMaximumSize(QtCore.QSize(100, 40))
        ingredientCard.setStyleSheet("font-family: \"CoconPro\";\n"
"color: black;\n"
"font-size: 12px;\n"
"border-radius: 8px;\n"
"background-color: white;\n"
"\n"
"")
        self.layoutWidget_8 = QtWidgets.QWidget(ingredientCard)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 0, 81, 41))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.bottle = QtWidgets.QLabel(self.layoutWidget_8)
        self.bottle.setStyleSheet("font-size: 10px;\n"
"background-color: transparent;")
        self.bottle.setAlignment(QtCore.Qt.AlignCenter)
        self.bottle.setObjectName("bottle")
        self.verticalLayout_7.addWidget(self.bottle)
        self.quantity = QtWidgets.QLabel(self.layoutWidget_8)
        self.quantity.setStyleSheet("font-size: 10px;\n"
"background-color: transparent;")
        self.quantity.setAlignment(QtCore.Qt.AlignCenter)
        self.quantity.setObjectName("quantity")
        self.verticalLayout_7.addWidget(self.quantity)

        self.retranslateUi(ingredientCard)
        QtCore.QMetaObject.connectSlotsByName(ingredientCard)

    def retranslateUi(self, ingredientCard):
        _translate = QtCore.QCoreApplication.translate
        ingredientCard.setWindowTitle(_translate("ingredientCard", "Frame"))
        self.bottle.setText(_translate("ingredientCard", "Schweppes"))
        self.quantity.setText(_translate("ingredientCard", "100 ml"))
